apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki-stack
  namespace: argocd
spec:
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
        pod-security.kubernetes.io/audit: privileged
        pod-security.kubernetes.io/warn: privileged
  destination:
    server: https://kubernetes.default.svc
    namespace: loki-stack
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: loki-stack
    targetRevision: 2.10.2
    plugin:
      name: argocd-vault-plugin-helm
      env:
        - name: HELM_VALUES
          value: |
            fluent-bit:
              enabled: true
            promtail:
              enabled: false
            grafana:
              enabled: true
              ingress:
                enabled: true
                ingressClassName: nginx
                annotations:
                  cert-manager.io/cluster-issuer: cloudflare
                hosts:
                  - grafana.cortado.<path:kv/cluster#domain>
                tls:
                  - secretName: grafana-tls
                    hosts:
                     - grafana.cortado.<path:kv/cluster#domain>  