apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sonarr-exporter
  namespace: argocd
spec:
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  source:
    repoURL: https://bjw-s.github.io/helm-charts
    chart: app-template
    targetRevision: 3.5.1
    plugin:
      name: argocd-vault-plugin-helm
      env:
        - name: HELM_VALUES
          value: |
          image:
            repository: ghcr.io/onedr0p/exportarr
            tag: v2.0.1
          args:
            - sonarr
            - --enable-additional-metrics
            - --enable-unknown-queue-items
          env:
            PORT: 9707
            URL: <path:kv/sonarr#url>
            APIKEY: <path:kv/sonarr#token>
          service:
            main:
              ports:
                http:
                  port: 9707
          serviceMonitor:
            main:
              enabled: true
              endpoints:
                - port: http
                  scheme: http
                  path: /metrics
                  interval: 5m
                  scrapeTimeout: 1m
          resources:
            requests:
              cpu: 10m
              memory: 100Mi
            limits:
              memory: 500Mi
