apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: factorio
  namespace: factorio
spec:
  sourcePVC: factorio-data
  trigger:
    schedule: "*/10 * * * *"
  restic:
    pruneIntervalDays: 7
    repository: restic-credentials
    retain:
      hourly: 2
      daily: 5
      weekly: 4
      monthly: 3
      yearly: 3
    copyMethod: Clone
