apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: restic-credentials
  namespace: vault
spec:
  refreshInterval: "30s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: restic-credentials
  data:
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: restic
        property: MINIO_HOME_ACCESSKEY
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: restic
        property: MINIO_HOME_SECRETKEY
    - secretKey: RESTIC_PASSWORD
      remoteRef:
        key: restic
        property: RESTIC_PASSWORD
    - secretKey: RESTIC_REPOSITORY
      remoteRef:
        key: restic
        property: RESTIC_REPOSITORY_VAULT
