apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: renovate
  namespace: argocd
spec:
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
  destination:
    server: https://kubernetes.default.svc
    namespace: renovate
  source:
    repoURL: https://bjw-s.github.io/helm-charts/
    chart: app-template
    targetRevision: 3.6.1
    helm:
      values: |
        controllers:
          renovate:
              containers:
                app:
                  image:
                    repository: renovate/renovate
                    tag: 39.104.1
                    pullPolicy: IfNotPresent
                  env:
                    MEND_RNV_ACCEPT_TOS: "y"
                    LOG_LEVEL: debug
                    MEND_RNV_PLATFORM: github
                    MEND_RNV_CRON_JOB_SCHEDULER: "0 */4 * * *"
                    MEND_RNV_CRON_APP_SYNC: "0 */4 * * *"
                    RENOVATE_AUTODISCOVER_FILTER: "qjoly/*"
                    RENOVATE_PAGINATE_ALL: "true"
                    GITHUB_COM_TOKEN: "<path:kv/renovate#github_pat>"
                    RENOVATE_PLATFORM: 'github'
                    RENOVATE_AUTODISCOVER: true
                    RENOVATE_TOKEN: "<path:kv/renovate#github_pat>"
                  resources:
                    requests:
                      cpu: 250m
                      memory: 500Mi
                    limits:
                      cpu: '2'
                      memory: 4Gi
        service:
          renovate:
            controller: renovate
            ports:
              http:
                port: 8080
        persistence:
          config:
            enabled: true
            type: configMap
            name: renovate-config
            globalMounts:
              - path: /usr/src/app/config.js
                subPath: config.js
          cache:
            enabled: true
            type: emptyDir
            globalMounts:
              - path: /tmp/renovate
        ingress:
          renovate:
            enabled: true
            className: nginx
            hosts:
              - host: "renovate.<path:kv/cluster#domain>"
                paths:
                  - path: /
                    service:
                      identifier: renovate
                      port: http
            tls:
              - secretName: renovate-tls
                hosts:
                  - "renovate.<path:kv/cluster#domain>"
        configMaps:
          config:
            enabled: true
            data:
              config.js: |
                module.exports = {
                  // Enter self-hosted configuration options here.
                  // https://docs.renovatebot.com/self-hosted-configuration/
                  autodiscover: true,
                  cacheHardTtlMinutes: 240,
                  onboardingConfigFileName: ".github/renovate.json",
                  detectHostRulesFromEnv: true,
                  onboardingRebaseCheckbox: true
                };
