apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sonarr-exporter
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: sonarr-exporter
  endpoints:
    - targetPort: 9707
      scrapeTimeout: 60s
      scrapeInterval: 120s
