apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: komga
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://rubxkube.github.io/charts/
    chart: komga
    targetRevision: 0.0.1
    helm:
      values: |
        common:
          ingress:
            enabled: true
            hostName: komga.thoughtless.eu
            ingressClassName: nginx
  destination:
    server: https://kubernetes.default.svc
    namespace: jackett
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
