apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: komga
  namespace: argocd
spec:
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  destination:
    server: https://kubernetes.default.svc
    namespace: komga
  source:
    repoURL: https://bjw-s.github.io/helm-charts/
    targetRevision: 3.5.1
    chart: app-template
    plugin:
      name: argocd-vault-plugin-helm
      env:
        - name: HELM_VALUES
          value: |
            controllers:
              komga:
                containers:
                  app:
                    image:
                      repository: gotson/komga
                      tag: "1.15.1@sha256:800b11aed7631888a071c12c138f7a6eef34cfc6878bc624ecf0989f93c741d6"
                    env:
                      TZ: ${TIMEZONE}
                      SERVER_PORT: 8080
                    resources:
                      requests:
                        cpu: 15m
                        memory: 1Gi
                      limits:
                        memory: 4Gi
            service:
              app:
                controller: komga
                ports:
                  http:
                    port: 8080
            ingress:
              app:
                className: nginx
                annotations:
                  external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
                  external-dns.alpha.kubernetes.io/hostname: komga.<path:kv/cloudflared#domain>
                  external-dns.alpha.kubernetes.io/target: 2f3b093d-bd57-4708-8d54-42723da21338.cfargotunnel.com
                hosts:
                  - host: "{{ .Release.Name }}.<path:kv/cloudflared#domain>"
                    paths:
                      - path: /
                        service:
                          identifier: app
                          port: http
            persistence:
              config:
                enabled: true
                existingClaim: ""
                globalMounts:
                  - path: /config
              comics:
                enabled: true
                existingClaim: ""
                globalMounts:
                  - path: /data
