apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: komga
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://rubxkube.github.io/charts/
    chart: komga
    targetRevision: 0.0.1
    helm:
      values: |
        common:
          ingress:
            enabled: true
            hostName: komga.thoughtless.eu
            ingressClassName: nginx
            tls:
              enabled: true
              secretName: "komga-tls"
            annotations:
              cert-manager.io/cluster-issuer: cloudflare
              external-dns.alpha.kubernetes.io/target: 54.36.168.210
  destination:
    server: https://kubernetes.default.svc
    namespace: komga
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
